### ISSUE TITLE
[BUG] Support search for waitForRequest (along with page.waitForRequest)

### ISSUE THREAD

**Issue by yury-s** [microsoft/playwright.dev#39] opened 2020-12-15 05:38 UTC
On the landing page do `ctrl+k` and type 'waitForRequest':

![waitForRequest-1](https://user-images.githubusercontent.com/9798949/102175429-6950a580-3e54-11eb-89a1-15f34268a79a.png)

Note that there are several indistinguishable entries. Hit `Enter` on the first one =>
![waitForRequest-2](https://user-images.githubusercontent.com/9798949/102175523-9309cc80-3e54-11eb-8e5c-7eb0740f8d0b.png)

(it scrolls to `page.touchscreen` instead of `waitForRequest`)

**Comment by arjunattam** [comment] 2020-12-17 17:48
Scroll is fixed with the new implementation, but only `page.waitForRequest` works (not just `waitForRequest`). I'll reframe this.

**Comment by arjunattam** [comment] 2020-12-18 09:49
Duplicate of #41

**Closed by arjunattam** 2020-12-18 09:49 UTC
